# Generated by Django 2.2.5 on 2019-11-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_auto_20191107_0143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
